name: LANraragi API Integration Tests

on:
  pull_request:
    branches: 
      - main
      - 'dev-*/main'
  push:
    branches: 
      - main
      - 'dev-*/main'
  schedule:
    - cron: '0 0 * * 5' # Run integration tests on main branch every Friday at 00:00
  workflow_call:  # Allow this workflow to be called by other workflows

jobs:
  integration-tests:

    strategy:
      matrix:
        pyver: ['3.12', '3.13']
        os: [ubuntu-latest] # only linux currently supports docker nicely
    
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    
    permissions:
      contents: read
      packages: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python ${{ matrix.pyver }}
        uses: actions/setup-python@v5
        with:
          allow-prereleases: true
          python-version: ${{ matrix.pyver }}
          
      - name: Install main package (aio-lanraragi)
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
          
      - name: Move to integration_tests and install test library
        run: |
          cd integration_tests
          pip install .
          
      - name: Run integration tests
        run: |
          cd integration_tests
          export CI=true
          pytest tests --log-cli-level=INFO --git-url=https://github.com/difegue/LANraragi.git --git-branch=dev --docker-api
        env:
          # Ensure Docker daemon is accessible to Python docker SDK
          DOCKER_HOST: unix:///var/run/docker.sock

  check:
    if: always()

    needs:
      - integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check if integration tests passed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJson(needs) }}


