name: Test Build and Publish to TestPyPI

on:
  push:
    branches:
      - main  # Publish to TestPyPI on every push to main
      - dev-0.1.3/cicd-test

jobs:
  # First, run integration tests to ensure quality
  integration-tests:
    uses: ./.github/workflows/lrr_integration_tests.yml
    
  # Build the package
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    needs: integration-tests
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          
      - name: Build package
        run: python -m build
        
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  # Publish to TestPyPI using trusted publishing
  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs: 
      - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/aio-lanraragi
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
      
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/ 